variable "sg-name" {}
variable "db-private-subnet-name1" {}
variable "db-private-subnet-name2" {}
variable "db-sg-name" {}
variable "rds-username" {}
variable "rds-pwd" {}
variable "db-name" {}
variable "rds-name" {}
variable "vpc-name" {}
