variable "vpc-name" {}
variable "vpc-cidr" {}
variable "igw-name" {}
variable "public-cidr1" {}
variable "public-subnet1" {}
variable "public-cidr2" {}
variable "public-subnet2" {}
variable "web-private-cidr1" {}
variable "web-private-subnet1" {}
variable "web-private-cidr2" {}
variable "web-private-subnet2" {}
variable "app-private-cidr1" {}
variable "app-private-subnet1" {}
variable "app-private-cidr2" {}
variable "app-private-subnet2" {}
variable "db-private-cidr1" {}
variable "db-private-subnet1" {}
variable "db-private-cidr2" {}
variable "db-private-subnet2" {}
variable "eip-name1" {}
variable "eip-name2" {}

variable "ngw-name1" {}
variable "ngw-name2" {}
variable "public-rt-name1" {}
variable "public-rt-name2" {}
variable "private-rt-name1" {}
variable "private-rt-name2" {}