variable "web-ami-name" {}
variable "app-ami-name" {}
variable "web-launch-template-name" {}
variable "app-launch-template-name" {}
variable "instance-profile-name" {}
variable "web-sg-name" {}
variable "app-sg-name" {}
variable "web-tg-name" {}
variable "app-tg-name" {}
variable "iam-role" {}
variable "public-subnet1" {}
variable "public-subnet2" {}
variable "web-private-subnet1" {}
variable "web-private-subnet2" {}
variable "app-private-subnet1" {}
variable "app-private-subnet2" {}
variable "web-asg-name" {}
variable "app-asg-name" {}
variable "image-id" {}